// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelProviderAuthStatus } from "./ModelProviderAuthStatus";

export type ModelProvider = { id: string, name: string, active: boolean, enabledInPicker: boolean, authStatus: ModelProviderAuthStatus, envKey: string | null, baseUrl: string | null, wireApi: string, modelCount: number, };
