// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApprovalRequestResolvedEvent = { 
/**
 * Call ID for the approval prompt that was resolved.
 */
call_id: string, };
