// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackgroundEventEvent = { message: string, 
/**
 * When true the background task that emitted this event has reached a
 * terminal state (completed / errored / shutdown).  The TUI uses this to
 * fire a desktop notification so the user knows the sub-agent finished.
 */
is_final: boolean, };
