// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestUserInputResolvedEvent = { 
/**
 * Turn ID for the request_user_input prompt that was resolved.
 */
turn_id: string, };
