// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubAgentActionPolicyAction } from "./SubAgentActionPolicyAction";
import type { SubAgentActionPolicyMode } from "./SubAgentActionPolicyMode";
import type { SubAgentActionPolicySource } from "./SubAgentActionPolicySource";

export type SubAgentActionPolicySnapshot = { version: number, mode: SubAgentActionPolicyMode, source: SubAgentActionPolicySource, allowed_actions?: Array<SubAgentActionPolicyAction>, denied_actions?: Array<SubAgentActionPolicyAction>, };
