// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubAgentActionPolicyAction = "agent_message_send" | "agent_followup_send" | "agent_close" | "agent_dismiss" | "agent_retry" | "agent_stop_all";
